### ISSUE TITLE
Cache Error

### ISSUE THREAD

**Issue by oleteacher** [ao/favicons#1]
Firstly, thank you! This is an excellent favicon alternative.

I have all working with no issue except the cache.

At default` $_CACHE_PATH = "cache";` the favicon is written in root directory. Even if I change to `$_CACHE_PATH = "../favcache";` the favicon is still written in root with the other files.

Running PHP 7.2.1 and Linux 16.04.1-Ubuntu

Any ideas how to solve?

Thanks,

Susan

**Comment by oleteacher** [comment]
Just got a insant message telling me to stay away from this code. A fellow teacher seems to ask how to fix caching issue and StackOverflow user https://stackoverflow.com/users/1255289/miken32 says:

Even the most basic tutorial would tell you that + is not a concatenation operator in PHP. Whoever wrote this, you don't want to use their code. For anything

https://stackoverflow.com/questions/55596402/favicon-php-cache-issue?noredirect=1#comment97890272_55596402

**Comment by ao** [comment]
The script has been updated with dot concatenation.
There are three examples at the top of the script to address directory paths.
